#!/bin/bash

export DTS_BOARD=stm32mp153a-stp-ddr-mx

if [ -z ${CROSS_COMPILE} ]; then
    export CROSS_COMPILE=arm-linux-gnueabihf-
fi
export ARCH=arm

if [ -f arch/arm/dts/${DTS_BOARD}.dts ]; then

    if [ -z $* ]; then
	[ -f .config ] || make stp_stm32mp153a_ddr_defconfig
    fi

    echo Build DDR calibration tools
    DEVICE_TREE=${DTS_BOARD} make $*
    [ -f u-boot-spl.stm32 ] && echo "Compiled done" && \
	echo "Run with: STM32_Programmer_CLI -c port=usb1 -d u-boot-spl.stm32 0x01 -g"
else
    echo "  You need place file ${DTS_BOARD}.dts"
    echo "(generated by CubeMX and fixed for stdout path) by writing"
    echo "	aliases {"
    echo "		serial0 = &uartX;"
    echo "		serial1 = &usartY;"
    echo "	};"
    echo
    echo "	chosen {"
    echo "		stdout-path = \"serialZ:115200n8\";"
    echo "	};"
    echo "into arch/arm/dts directory and run this again."
fi